### ISSUE TITLE
Client can't connect to server.

### ISSUE THREAD

**Issue by valkyrienyanko** [Raccoons-Rise-Up/server#18]
Sometimes the client times out on connection to the server.

Clicking in the server console window solves this.

This seemingly happens randomly. The cause is unknown.

**Comment by 0HyperCube** [comment]
@valkyrienyanko Try turning of quick edit mode
- https://superuser.com/questions/312132/command-prompt-hangs-until-keypress
- https://serverfault.com/questions/314194/why-does-windows-command-prompt-stalls-until-a-key-is-pressed-when-executing-lon

**Comment by valkyrienyanko** [comment]
Turning off quick edit mode did not solve this for me.

**Comment by valkyrienyanko** [comment]
Maybe if I somehow force the window in a focused state on startup the issue will go away.
