### ISSUE TITLE
TEXT FIELD: ArgumentOutOfRangeException if Window Width is Too Thin

### ISSUE THREAD

**Issue by valkyrienyanko** [Raccoons-Rise-Up/server#2]
**If console is resized to have a small width this error appears when a new message is sent.**

System.ArgumentOutOfRangeException: 'The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'left') Actual value was 34.'

https://github.com/Kittens-Rise-Up/server/blob/7231fcdb94ea82e2fa1323a61b3f49b97b744bda/src/Logger/Logger.cs#L111

## Update
Issue is `s_TextFieldHeight` is becoming super large when window gets really thin because text has to wrap many times thus going negative and out of bounds.

## Update
This line also causes similar error.
https://github.com/Kittens-Rise-Up/server/blob/b5d7919e75c0ce18571ed0bea6164d5d04cc5cc3/src/Logger/Logger.cs#L251

**Comment by dpspcghst** [comment]
What is the console's buffer size in said dimension? It [might be helpful](https://stackoverflow.com/questions/62168358/what-is-system-argumentoutofrangeexception-index-was-out-of-range-must-be-no) to add/modify the code to better handle the range.

**Comment by valkyrienyanko** [comment]
> What is the console's buffer size in said dimension? It [might be helpful](https://stackoverflow.com/questions/62168358/what-is-system-argumentoutofrangeexception-index-was-out-of-range-must-be-no) to add/modify the code to better handle the range.

@deepspaceghost I was thinking of using line breaks (`Environment.NewLine`) if I were to continue with a text field box that has a height greater than 1 but I was also thinking it would be a better idea to have the text field input all on one line that scrolls from left to right as you exceed window width.
