### ISSUE TITLE
CONSOLE: Add profiling tools

### ISSUE THREAD

**Issue by valkyrienyanko** [Raccoons-Rise-Up/server#6]
For example measure how long a snippet of code takes to execute.

I'm sure there are other profiling tools but I can't think of any right now.

**Comment by 0HyperCube** [comment]
Can't you just use the stopwatch class? - https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch?view=net-5.0

**Comment by valkyrienyanko** [comment]
Yes this looks good, you can add this right now if you want. I am not sure how this would get implemented though. Maybe something like `Debug.Timer.Start()` `Debug.Timer.Stop()` `Debug.Timer.Print()` for ease of use. Or even `DebugTimer.(...)` or `Debug.(...)` I'm not sure.
